const publicRuntimeConfig = {
    REACT_APP_HASURA_ADMIN_SECRET: process.env.REACT_APP_HASURA_ADMIN_SECRET,
    REACT_APP_HASURA_END_POINT: process.env.REACT_APP_HASURA_END_POINT,
};

export const { REACT_APP_HASURA_ADMIN_SECRET, REACT_APP_HASURA_END_POINT } = publicRuntimeConfig;
