name: FCode Storybook

on:
    pull_request_review:
        types: [submitted]

jobs:
    install-deps:
        name: Install dependencies
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
              with:
                  persist-credentials: false

            - name: Config github private repo
              env:
                  GITHUB_TOKEN: ${{ secrets.SP_GITHUB_TOKEN }}
                  GITHUB_EMAIL: ${{ secrets.SP_GITHUB_EMAIL }}

            - name: Install root dependencies
              run: yarn --frozen-lockfile

            - uses: actions/cache@v2
              with:
                  path: |
                      ${{github.workspace}}/node_modules
                      ~/.cache/Cypress
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    unit-test:
        name: Unit Test
        needs:
            - install-deps
        continue-on-error: false
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
              with:
                  persist-credentials: false

            - uses: actions/cache@v2
              id: restore-deps
              with:
                  path: |
                      ${{github.workspace}}/node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Unit test
              run: yarn test:unit-ci

    build:
        name: Build
        continue-on-error: false
        needs:
            - unit-test
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
              with:
                  persist-credentials: false

            - uses: actions/cache@v2
              id: restore-deps
              with:
                  path: |
                      ${{github.workspace}}/node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - uses: actions/cache@v2
              id: restore-build
              with:
                  path: "**/build"
                  key: ${{ runner.os }}-build-${{ github.sha }}

            - name: Build
              run: yarn build
